[Card-3] add code documentation
DevCrew-io/material-text-fields pull request #1
Opened 2023-03-16 05:18 UTC by AliRehan-DevCrew

2023-03-16 05:23 UTC, AliRehan-DevCrew commented
![](https://github.trello.services/images/mini-trello-icon.png) [Material Text Field Widget](https://trello.com/c/o2T3kTSW/3-material-text-field-widget)

2023-03-16 13:36 UTC, WaseemAbbas-DevCrew requested changes

2023-03-16 13:36 UTC, WaseemAbbas-DevCrew commented on lib/labeled_text_field.dart
>    final Widget child;
if it's required to provide a `MaterialTextField` object then why not we set its types to be `MaterialTextField` or `TextField` rather than Widget.

2023-03-17 09:36 UTC, WaseemAbbas-DevCrew approved these changes
nicely done @AliRehan-DevCrew

2023-03-17 09:38 UTC, merged