feature : add errorBorder to _MaterialTextFieldTheme
DevCrew-io/material-text-fields pull request #13
Opened 2023-08-03 13:39 UTC by nick-beznos

Corresponding issue -  #10

2023-08-04 07:20 UTC, WaseemAbbas-DevCrew requested changes

2023-08-04 07:20 UTC, WaseemAbbas-DevCrew commented on lib/theme/material_text_field_theme.dart
> +    InputBorder? errorBorder,
here `InputBorder? errorBorder` should be replaced with Color? `errorBorderColor` as we did the same for `focusedBorder` and `enabledBorder`. This makes sure that all borders (i.e. errorBorder, focusedBorder, and enabledBorder) have the same border-radius and stoke.

2023-08-04 07:20 UTC, WaseemAbbas-DevCrew commented on lib/theme/material_text_field_theme.dart
> +          errorBorder: errorBorder,
Then here do like this:

```Dart
      errorBorder: OutlineInputBorder(
            borderSide: BorderSide(
                width: width, color: errorBorderColor ?? Colors.transparent),
            borderRadius: BorderRadius.circular(radius),
      ),
```

2023-09-28 06:31 UTC, nick-beznos commented
Sorry for a such a long pause.

2023-09-28 07:02 UTC, WaseemAbbas-DevCrew approved these changes

2023-09-28 07:04 UTC, WaseemAbbas-DevCrew commented
Nice work @nick-beznos. Thank you!

2023-09-28 07:05 UTC, merged