[Card-15] Publish Package
DevCrew-io/material-text-fields pull request #2
Opened 2023-03-17 11:22 UTC by AliRehan-DevCrew

Update Following file's

 - README.md
 - Example README.md
 - LICENSE 
 - CHANGELOG

2023-03-17 11:25 UTC, AliRehan-DevCrew commented
![](https://github.trello.services/images/mini-trello-icon.png) [Publish Package "Material Text Field"](https://trello.com/c/xws29Jyz/15-publish-package-material-text-field)

2023-03-20 09:39 UTC, WaseemAbbas-DevCrew commented
@taimoor-dc please take a look at the docs.

2023-03-20 10:10 UTC, arslandevcrew reviewed
please attach default behaviour of material text field attach with screenshots.

2023-03-21 07:44 UTC, AliRehan-DevCrew commented
@taimoor-dc 
@WaseemAbbas-DevCrew 
https://github.com/DevCrew-io/material-text-fields/blob/card-15-publish-package/README.md
https://github.com/DevCrew-io/material-text-fields/blob/card-15-publish-package/example/README.md
https://github.com/DevCrew-io/material-text-fields/blob/card-15-publish-package/CHANGELOG.md
https://github.com/DevCrew-io/material-text-fields/blob/card-15-publish-package/LICENSE

2023-03-21 10:05 UTC, WaseemAbbas-DevCrew requested changes
@AliRehan-DevCrew, please do the requested changes in all files where needed.

2023-03-21 10:05 UTC, WaseemAbbas-DevCrew commented on README.md
> +Material Text Field is a customizable widget for text input values in Dart. You can define the styling of the text field in your app's theme file or create multiple text fields with different styling
remove **With this package,**

2023-03-21 10:05 UTC, WaseemAbbas-DevCrew commented on README.md
> +Then run flutter pub get to install the package.
move the `flutter pub get` command into the inline code block.

2023-03-21 10:05 UTC, WaseemAbbas-DevCrew commented on README.md
> +                hint: "Email",
use single quotes for strings

2023-03-21 10:05 UTC, WaseemAbbas-DevCrew commented on README.md
> +                controller: _emailController,
rename `_emailController` to `_emailTextController`

2023-03-21 10:05 UTC, WaseemAbbas-DevCrew commented on README.md
> +                prefixIcon: Image.asset(ImagePath.icEmail),
use a hard-coded string value instead of a variable like:

`prefixIcon: Image.asset('assets/images/ic_email.png'),`

2023-03-21 10:05 UTC, WaseemAbbas-DevCrew commented on README.md
> +                  labelText: "Password",
use single quotes

2023-03-21 10:05 UTC, WaseemAbbas-DevCrew commented on README.md
> +                  suffixIcon: Image.asset(ImagePath.icLock),
use a hard-coded string value for the image path like `assets/images/ic_lock.png`

2023-03-21 10:54 UTC, arslandevcrew approved these changes

2023-03-21 11:03 UTC, WaseemAbbas-DevCrew approved these changes

2023-03-21 11:04 UTC, merged